# Generated by Django 4.1.4 on 2022-12-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
